### ISSUE TITLE
spring-utils dependency

### ISSUE THREAD

**Issue by dongfg** [cncduLee/zk-ucc#2]
The dependency define in zk-ucc/pom.xml,I can not find it in The Central Repository and I find it unused.

```
<dependency>
<groupId>org.springframework</groupId>
<artifactId>spring-utils</artifactId>
<version>${spring-version}</version>
</dependency>
```

**Comment by lipengming** [comment]
yes ,i will fix it later.thanks!

**Comment by webjoin** [comment]
Hi , Have you fixed it now ?   I cloned it , but it does not  work now .
